version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: db_recetas
    ports:
      - "5432:5432"
    volumes:
      - db_data_recetas:/var/lib/postgresql/data
      # Este script creará nuestra nueva tabla 'recipes'
      - ./backend/db_schema.sql:/docker-entrypoint-initdb.d/db_schema.sql

  backend:
    build: ./backend
    restart: always
    environment:
      # Variables para que el backend se conecte a la DB
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: admin123
      DB_NAME: db_recetas
      DB_PORT: 5432
    ports:
      - "3001:3001"
    depends_on:
      - db

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      # La URL que el navegador usará para contactar al backend
      REACT_APP_API_URL: http://localhost:3001
    depends_on:
      - backend

volumes:
  db_data_recetas: