name: Despliegue Completo (Front & Back)

on:
  push:
    branches: [ main ]

jobs:
  # === TRABAJO 1: DESPLEGAR FRONTEND EN GITHUB PAGES ===
  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias (Frontend)
        working-directory: ./frontend
        run: npm install

      - name: Construir proyecto (Build)
        working-directory: ./frontend
        env:
          # Aquí se inyecta la URL de tu backend
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
          CI: false
          NODE_OPTIONS: "--openssl-legacy-provider"  # <--- ¡AGREGA ESTA LÍNEA!
        run: npm run build

      - name: Desplegar a GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: frontend/build
          branch: gh-pages # La rama donde vivirá la web final

  # === TRABAJO 2: DESPLEGAR BACKEND EN RENDER ===
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Disparar Deploy Hook de Render
        # Esto es un simple "toque" a la URL de Render para que actualice
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}